Previous build failed with "./tools/android-wait-for-emulator.sh: No such file or directory" Making more like sample travis config at https://travis-ci.org/ankidroid/Anki-Android/builds/624268367/config

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,6 +1,3 @@
-
-# Based on https://travis-ci.org/ankidroid/Anki-Android/builds/624268367
-# See also https://travis-ci.community/t/is-android-28-emulator-supported/1718/6
 sudo: true
 language: bash
 # ignored on non-linux platforms, but bionic is required for nested virtualization
@@ -28,31 +25,7 @@ env:
     - UNIT_TEST=FALSE # by default we don't run the unit tests, they are run only in specific builds
     - FINALIZE_COVERAGE=FALSE # by default we don't finalize coverage, it is done in one specific build
   matrix:
-    - API=25
-    - API=27
-    - API=28
-    - API=29
-    - API=25 JDK="1.11" # make sure we work in the future
-
-jobs:
-  fast_finish: true  # Report success without waiting for jobs that allowed to fail.
-  include:
-    # The "test" stage is implicit and gets the main matrix. This adds extra stages/jobs
-    - stage: unit_test
-      env: UNIT_TEST=TRUE API=NONE
-      install: skip
-      os: windows
-    - stage: unit_test
-      env: UNIT_TEST=TRUE API=NONE
-      install: skip
-      os: linux
-    - stage: finalize_coverage
-      env: FINALIZE_COVERAGE=TRUE API=NONE
-      install: skip
-      script: echo finalize codacy coverage uploads
-  allow_failures:
-    - env: API=25 JDK="1.11" # non-default JDKs should not hold up success reporting
-    - env: FINALIZE_COVERAGE=TRUE API=NONE # finalizing coverage should not hold up success reporting
+   - API=25
 
 before_install:
   # This section may run on all platforms, and may run for unit tests or for coverage finalization
@@ -108,40 +81,47 @@ install:
   - source ~/.install-jdk-travis.sh
 
 script:
-  - |
-    if [ "$UNIT_TEST" = "TRUE" ]; then
-      echo "No unit tests yet..."
-    fi
+- |
+  ./gradlew build assembleAndroidTest
+  retval=$?
+  if [ $retval -ne 0 ]; then
+    echo "error on assembling, exit code: "$retval
+    exit $retval
+  fi
 
-  - |
-    if [ "$API" != "NONE" ]; then
-      ./gradlew build assembleAndroidTest
-      retval=$?
-      if [ $retval -ne 0 ]; then
-        echo "error on assembling, exit code: "$retval
-        exit $retval
-      fi
-      # ---
-      adb shell am instrument -w -r -e debug false org.andstatus.todoagenda.tests/androidx.test.runner.AndroidJUnitRunner |& tee build/adb-test.log
-      retval=$?
-      if [ $retval -ne 0 ]; then
-        echo "error in adb, exit code: "$retval
-        exit $retval
-      fi
-      # ---
-      # adb doesn't propagate exit code from tests, see https://code.google.com/p/android/issues/detail?id=3254
-      # So we need to parse saved terminal log
-      cat build/adb-test.log | grep "INSTRUMENTATION_STATUS: stack=" | grep -v "org.junit.AssumptionViolatedException"
-      if [ $? -eq 0 ]; then
-        echo "Test failure found"
-        exit 1
-      else
-        cat build/adb-test.log | grep "OK ("
-      fi
-    fi
+# See http://stackoverflow.com/questions/21294945/error-unable-to-find-instrumentation-info-for-componentinfo
+# Instead of this (which doesn't give any output during tests execution):
+# - ./gradlew connectedCheck -PdisablePreDex --continue --stacktrace --debug
+# run:
+- |
+  ./gradlew :app:installDebug :app:installDebugAndroidTest
+  retval=$?
+  if [ $retval -ne 0 ]; then
+    echo "error on install, exit code: "$retval
+    exit $retval
+  fi
+
+- |
+  adb shell am instrument -w -r -e debug false org.andstatus.todoagenda.tests/androidx.test.runner.AndroidJUnitRunner |& tee build/adb-test.log
+  retval=$?
+  if [ $retval -ne 0 ]; then
+    echo "error in adb, exit code: "$retval
+    exit $retval
+  fi
+
+# adb doesn't propagate exit code from tests, see https://code.google.com/p/android/issues/detail?id=3254
+# So we need to parse saved terminal log
+- |
+  cat build/adb-test.log | grep "INSTRUMENTATION_STATUS: stack=" | grep -v "org.junit.AssumptionViolatedException"
+  if [ $? -eq 0 ]; then
+    echo "Test failure found"
+    exit 1
+  else
+    cat build/adb-test.log | grep "OK ("
+  fi
 
 after_success:
-  # Nothing here yet
+  echo "After success"
 
 before_cache:
   - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
