Update Travis-CI. Using template from https://travis-ci.org/ankidroid/Anki-Android/builds/624268367/config

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,88 +1,161 @@
-language: android
-jdk:
-- oraclejdk8
+
+# Based on https://travis-ci.org/ankidroid/Anki-Android/builds/624268367
+# See also https://travis-ci.community/t/is-android-28-emulator-supported/1718/6
+sudo: true
+language: bash
+# ignored on non-linux platforms, but bionic is required for nested virtualization
+dist: bionic
+
+stages:
+  - install
+  - unit_test # custom stage defined in jobs::include section
+  - test
+  - finalize_coverage # custom stage defined in jobs::include section
+  - cache
+
 env:
   global:
-  - ANDROID_API=29
-  - EMULATOR_API=25
-  - ANDROID_BUILD_TOOLS=29.0.2
-  - ANDROID_ABI=x86_64
-  - EMU_FLAVOR=default
-  - IMAGE_TAG=google_apis-$EMULATOR_API
-android:
-  components:
-  - tools
-  - android-$EMULATOR_API
-  - platform-tools
-  - tools
-  - build-tools-$ANDROID_BUILD_TOOLS
-  - android-$ANDROID_API
-  - extra-android-support
-  - extra-android-m2repository
-  - extra-google-m2repository
-  - sys-img-$ANDROID_ABI-$IMAGE_TAG
-  licenses:
-  - ".+"
-before_script:
-- echo "y" | android update sdk -a --no-ui --filter android-$EMULATOR_API
-- echo "y" | android update sdk -a --no-ui --filter sys-img-$ANDROID_ABI-$IMAGE_TAG
-- android list targets
-- echo no | avdmanager create avd --force -n test -k "system-images;$IMAGE_TAG;$EMU_FLAVOR;$ANDROID_ABI" -c 10M
-- emulator -avd test -no-skin -no-window &
-- android-wait-for-emulator
-- adb shell input keyevent 82 &
-- adb wait-for-device get-serialno
-- cd ${TRAVIS_BUILD_DIR}
-- chmod +x gradlew
-- ./gradlew --version
-- ./gradlew clean
+    - ABI=x86_64
+    - ADB_INSTALL_TIMEOUT=8
+    - ANDROID_HOME=${HOME}/android-sdk
+    - ANDROID_TOOLS_URL="https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"
+    - EMU_FLAVOR=default # use google_apis flavor if no default flavor emulator
+    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
+    - JDK="1.8"
+    - TOOLS=${ANDROID_HOME}/tools
+    # PATH order is incredibly important. e.g. the 'emulator' script exists in more than one place!
+    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
+    - UNIT_TEST=FALSE # by default we don't run the unit tests, they are run only in specific builds
+    - FINALIZE_COVERAGE=FALSE # by default we don't finalize coverage, it is done in one specific build
+  matrix:
+    - API=25
+    - API=27
+    - API=28
+    - API=29
+    - API=25 JDK="1.11" # make sure we work in the future
+
+jobs:
+  fast_finish: true  # Report success without waiting for jobs that allowed to fail.
+  include:
+    # The "test" stage is implicit and gets the main matrix. This adds extra stages/jobs
+    - stage: unit_test
+      env: UNIT_TEST=TRUE API=NONE
+      install: skip
+      os: windows
+    - stage: unit_test
+      env: UNIT_TEST=TRUE API=NONE
+      install: skip
+      os: osx
+    - stage: unit_test
+      env: UNIT_TEST=TRUE API=NONE
+      install: skip
+      os: linux
+    - stage: finalize_coverage
+      env: FINALIZE_COVERAGE=TRUE API=NONE
+      install: skip
+      script: echo finalize codacy coverage uploads
+  allow_failures:
+    - env: API=25 JDK="1.11" # non-default JDKs should not hold up success reporting
+    - env: FINALIZE_COVERAGE=TRUE API=NONE # finalizing coverage should not hold up success reporting
+
+before_install:
+  # This section may run on all platforms, and may run for unit tests or for coverage finalization
+  # It should not make assumptions about os platform or desired tool installation
+
+  # Set up JDK 8 for Android SDK - Java is universally needed: codacy, unit tests, emulators
+  - curl "${GRAVIS}.install-jdk-travis.sh" --output ~/.install-jdk-travis.sh
+  - export TARGET_JDK="${JDK}"
+  - JDK="1.8"
+  - source ~/.install-jdk-travis.sh
+
+  # Set up Android SDK - this is needed everywhere but coverage finalization, so toggle on that
+  - if [ "$FINALIZE_COVERAGE" = "FALSE" ]; then wget -q "${ANDROID_TOOLS_URL}" -O android-sdk-tools.zip; fi
+  - if [ "$FINALIZE_COVERAGE" = "FALSE" ]; then unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}; fi
+  - if [ "$FINALIZE_COVERAGE" = "FALSE" ]; then rm android-sdk-tools.zip; fi
+  - if [ "$FINALIZE_COVERAGE" = "FALSE" ]; then mkdir ~/.android; fi # avoid harmless sdkmanager warning
+  - if [ "$FINALIZE_COVERAGE" = "FALSE" ]; then echo 'count=0' > ~/.android/repositories.cfg; fi # avoid harmless sdkmanager warning
+  - if [ "$FINALIZE_COVERAGE" = "FALSE" ]; then yes | sdkmanager --licenses >/dev/null; fi # accept all sdkmanager warnings
+  - if [ "$FINALIZE_COVERAGE" = "FALSE" ]; then echo y | sdkmanager --no_https "platform-tools" >/dev/null; fi
+  - if [ "$FINALIZE_COVERAGE" = "FALSE" ]; then echo y | sdkmanager --no_https "tools" >/dev/null; fi # A second time per Travis docs, gets latest versions
+  - if [ "$FINALIZE_COVERAGE" = "FALSE" ]; then echo y | sdkmanager --no_https "build-tools;28.0.3" >/dev/null; fi # Implicit gradle dependency - gradle drives changes
+  - if [ "$FINALIZE_COVERAGE" = "FALSE" ]; then echo y | sdkmanager --no_https "platforms;android-28" >/dev/null; fi # We need the API of the current compileSdkVersion from gradle.properties
+
+install:
+  # In our setup, install only runs on matrix entries we want full emulator tests on
+  # That only happens currently on linux, so this section can assume linux + emulator is desired
+  # Download required emulator tools
+  - echo y | sdkmanager --no_https "platforms;android-$API" >/dev/null # We need the API of the emulator we will run
+  - echo y | sdkmanager --no_https "emulator" >/dev/null
+  - echo y | sdkmanager --no_https "system-images;android-$API;$EMU_FLAVOR;$ABI" >/dev/null # install our emulator
+
+  # Set up KVM on linux for hardware acceleration. Manually here so it only happens for emulator tests, takes ~30s
+  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends install bridge-utils libpulse0 libvirt-bin qemu-kvm virtinst ubuntu-vm-builder
+  - sudo adduser $USER libvirt
+  - sudo adduser $USER kvm
+
+  # Create an Android emulator
+  - echo no | avdmanager create avd --force -n test -k "system-images;android-$API;$EMU_FLAVOR;$ABI" -c 10M
+  - |
+    EMU_PARAMS="-verbose -no-snapshot -no-window -camera-back none -camera-front none -selinux permissive -qemu -m 2048"
+    EMU_COMMAND="emulator"
+    # This double "sudo" monstrosity is used to have Travis execute the
+    # emulator with its new group permissions and help preserve the rule
+    # of least privilege.
+    sudo -E sudo -u $USER -E bash -c "${ANDROID_HOME}/emulator/${EMU_COMMAND} -avd test ${AUDIO} ${EMU_PARAMS} &"
+
+  # Wait for emulator to be ready
+  - ./tools/android-wait-for-emulator.sh
+  - adb shell input keyevent 82 &
+
+  # Switch back to our target JDK version to build and run tests
+  - JDK="${TARGET_JDK}"
+  - source ~/.install-jdk-travis.sh
+
 script:
-- |
-  ./gradlew build assembleAndroidTest
-  retval=$?
-  if [ $retval -ne 0 ]; then
-    echo "error on assembling, exit code: "$retval
-    exit $retval
-  fi
+  - |
+    if [ "$UNIT_TEST" = "TRUE" ]; then
+      # Nothing here yet...
+    fi
 
-# See http://stackoverflow.com/questions/21294945/error-unable-to-find-instrumentation-info-for-componentinfo
-# Instead of this (which doesn't give any output during tests execution):
-# - ./gradlew connectedCheck -PdisablePreDex --continue --stacktrace --debug
-# run:
-- |
-  ./gradlew :app:installDebug :app:installDebugAndroidTest
-  retval=$?
-  if [ $retval -ne 0 ]; then
-    echo "error on install, exit code: "$retval
-    exit $retval
-  fi
+  - |
+    if [ "$API" != "NONE" ]; then
+      ./gradlew build assembleAndroidTest
+      retval=$?
+      if [ $retval -ne 0 ]; then
+        echo "error on assembling, exit code: "$retval
+        exit $retval
+      fi
+      # ---
+      adb shell am instrument -w -r -e debug false org.andstatus.todoagenda.tests/androidx.test.runner.AndroidJUnitRunner |& tee build/adb-test.log
+      retval=$?
+      if [ $retval -ne 0 ]; then
+        echo "error in adb, exit code: "$retval
+        exit $retval
+      fi
+      # ---
+      # adb doesn't propagate exit code from tests, see https://code.google.com/p/android/issues/detail?id=3254
+      # So we need to parse saved terminal log
+      cat build/adb-test.log | grep "INSTRUMENTATION_STATUS: stack=" | grep -v "org.junit.AssumptionViolatedException"
+      if [ $? -eq 0 ]; then
+        echo "Test failure found"
+        exit 1
+      else
+        cat build/adb-test.log | grep "OK ("
+      fi
+    fi
 
-- |
-  adb shell am instrument -w -r -e debug false org.andstatus.todoagenda.tests/androidx.test.runner.AndroidJUnitRunner |& tee build/adb-test.log
-  retval=$?
-  if [ $retval -ne 0 ]; then
-    echo "error in adb, exit code: "$retval
-    exit $retval
-  fi
+after_success:
+  # Nothing here yet
 
-# adb doesn't propagate exit code from tests, see https://code.google.com/p/android/issues/detail?id=3254
-# So we need to parse saved terminal log
-- |
-  cat build/adb-test.log | grep "INSTRUMENTATION_STATUS: stack=" | grep -v "org.junit.AssumptionViolatedException"
-  if [ $? -eq 0 ]; then
-    echo "Test failure found"
-    exit 1
-  else
-    cat build/adb-test.log | grep "OK ("
-  fi
+before_cache:
+  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
+  - curl "${GRAVIS}.clean_gradle_cache.sh" --output ~/.clean_gradle_cache.sh
+  - bash ~/.clean_gradle_cache.sh > /dev/null
+
+cache:
+  directories:
+    - $HOME/.gradle/caches/
+    - $HOME/.gradle/wrapper/
 
 notifications:
   email: false
-cache:
-  directories:
-  - $HOME/.m2
-  - $HOME/.gradle/caches/
-  - $HOME/.gradle/wrapper/
-  - $HOME/.android/build-cache
-before_install:
-- yes | sdkmanager "platforms;android-$ANDROID_API"
