Fix Travis CI build

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,104 +1,66 @@
-# This build file is based on https://github.com/andstatus/andstatus/blob/master/.travis.yml
 language: android
-jdk: oraclejdk8
-
-sudo: required
-
+jdk:
+- oraclejdk8
 env:
   global:
-    - COMPILE_API_LEVEL=25
-    - ANDROID_BUILD_TOOLS_VERSION=25.0.3
-    # Using Emulator for an older Android version, because there is no newer emulator, which works in travis-ci
-    - EMULATOR_API_LEVEL=24
-    - EMULATOR_ABI=armeabi-v7a
-    - EMULATOR_TAG=google_apis
-    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
-
+  - ANDROID_API=27
+  - EMULATOR_API=24
+  - ANDROID_BUILD_TOOLS=28.0.3
 android:
   components:
-    - tools
-    - platform-tools
-    - tools
-    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
-    - android-$COMPILE_API_LEVEL
-    - android-$EMULATOR_API_LEVEL
-    - extra-google-m2repository
-    - extra-android-m2repository
-    # Specify at least one system image
-    - sys-img-$EMULATOR_ABI-google_apis-$EMULATOR_API_LEVEL
-
-before_install:
-  # http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
-  - chmod +x app/calendar-widget/gradlew
-
+  - tools
+  - android-$EMULATOR_API
+  - platform-tools
+  - tools
+  - build-tools-$ANDROID_BUILD_TOOLS
+  - android-$ANDROID_API
+  - extra-android-support
+  - extra-android-m2repository
+  - extra-google-m2repository
+  - sys-img-armeabi-v7a-android-$EMULATOR_API
+  licenses:
+  - ".+"
 before_script:
-  - uname -a
-  - android list targets
-  - ls -la $HOME/.android/**/*
-  - ls -la $HOME/**/*
-  # Create and start emulator
-  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $EMULATOR_ABI --tag $EMULATOR_TAG
-  - ls -la $HOME/.android/**/*
-  - ls -la $HOME/**/*
-  - cat $HOME/.android/avd/test.avd/config.ini
-  - cp assets/avd_config.ini $HOME/.android/avd/test.avd/config.ini
-  - cat $HOME/.android/avd/test.avd/config.ini
-  - emulator -avd test -no-window &
-  - travis_wait 30 android-wait-for-emulator
-  # Previous command seems to end too early, so wait a bit more
-  # On multilined commands: https://gitlab.com/gitlab-org/gitlab-ci/issues/258 and http://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines
-  - |
-    while ! adb shell getprop init.svc.bootanim; do
-      echo Waiting for boot animation to end
-      sleep 10
-    done
-  # Another method. Should print SDK version number to console
-  # See http://stackoverflow.com/questions/28195080/unknown-api-level-error-when-trying-to-run-instrumentation-test
-  - |
-    while ! adb shell getprop ro.build.version.sdk; do
-      echo Waiting for ro.build.version.sdk value from device
-      sleep 10
-    done
-  - adb devices
-  - adb shell input keyevent 82 &
-
+- echo "y" | android update sdk -a --no-ui --filter android-$EMULATOR_API
+- echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-$EMULATOR_API
+- android list targets | grep -E '^id:' | awk -F '"' '{$1=""; print $2}' # list all targets
+- echo no | android create avd --force -n test -t android-$EMULATOR_API --abi armeabi-v7a
+- emulator -avd test -no-skin -no-window &
+- android-wait-for-emulator
+- adb shell input keyevent 82 &
+- adb wait-for-device get-serialno
+- cd ${TRAVIS_BUILD_DIR}
+- chmod +x gradlew
+- ./gradlew --version
+- ./gradlew clean
 script:
-  - cd app/calendar-widget
-  - |
-    ./gradlew build assembleAndroidTest
-    retval=$?
-    if [ $retval -ne 0 ]; then
-      echo "error on assembling, exit code: "$retval
-      exit $retval
-    fi
+- |
+  ./gradlew build assembleAndroidTest
+  retval=$?
+  if [ $retval -ne 0 ]; then
+    echo "error on assembling, exit code: "$retval
+    exit $retval
+  fi
 
-  # See http://stackoverflow.com/questions/21294945/error-unable-to-find-instrumentation-info-for-componentinfo
-  # Instead of this (which doesn't give any output during tests execution):
-  # - ./gradlew connectedCheck -PdisablePreDex --continue --stacktrace --debug
-  # run:
-  - |
-    ./gradlew :installDebugAndroidTest :installDebug
-    retval=$?
-    if [ $retval -ne 0 ]; then
-      echo "error on install, exit code: "$retval
-      exit $retval
-    fi
+# See http://stackoverflow.com/questions/21294945/error-unable-to-find-instrumentation-info-for-componentinfo
+# Instead of this (which doesn't give any output during tests execution):
+# - ./gradlew connectedCheck -PdisablePreDex --continue --stacktrace --debug
+# run:
+- |
+  ./gradlew :app:installDebug :app:installDebugAndroidTest
+  retval=$?
+  if [ $retval -ne 0 ]; then
+    echo "error on install, exit code: "$retval
+    exit $retval
+  fi
 
-  #
-  # The below line causes Process crash due to absense of video device
-  #- adb shell am instrument -w -r -e debug false org.andstatus.app.tests/android.test.InstrumentationTestRunner
-  #
-  # Run only tests, marked with a special annotation:
-  # See https://developer.android.com/reference/android/test/InstrumentationTestRunner.html
-  # For testing one method only:
-  # - adb shell am instrument -w -r -e debug false -e class org.andstatus.app.msg.ActAsUserTest#testActAsUser org.andstatus.app.tests/android.test.InstrumentationTestRunner
-  - |
-    adb shell am instrument -w -r -e debug false org.andstatus.todoagenda.tests/android.test.InstrumentationTestRunner |& tee build/adb-test.log
-    retval=$?
-    if [ $retval -ne 0 ]; then
-      echo "error in adb, exit code: "$retval
-      exit $retval
-    fi
+- |
+  adb shell am instrument -w -r -e debug false org.andstatus.todoagenda.tests/android.test.InstrumentationTestRunner |& tee build/adb-test.log
+  retval=$?
+  if [ $retval -ne 0 ]; then
+    echo "error in adb, exit code: "$retval
+    exit $retval
+  fi
 
   # adb doesn't propagate exit code from tests, see https://code.google.com/p/android/issues/detail?id=3254
   # So we need to parse saved terminal log
@@ -111,12 +73,13 @@ script:
       cat build/adb-test.log | grep "Test results for InstrumentationTestRunner"
     fi
 
-# See https://docs.travis-ci.com/user/languages/java/#Projects-Using-Gradle
-before_cache:
-  - ls -la $HOME/.gradle/**/*
-  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
-  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
+notifications:
+  email: false
 cache:
   directories:
-    - $HOME/.gradle/caches/
-    - $HOME/.gradle/wrapper/
+  - $HOME/.m2
+  - $HOME/.gradle/caches/
+  - $HOME/.gradle/wrapper/
+  - $HOME/.android/build-cache
+before_install:
+- yes | sdkmanager "platforms;android-27"
